// Generated by https://quicktype.io

export interface PublicationsResponse {
  data: Datum[];
  meta: Meta;
}

export interface Datum {
  id: number;
  attributes: Attributes;
}

export interface Attributes {
  title: string;
  content: Content[];
  slug: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
}

export interface Content {
  type: string;
  children: Child[];
}

export interface Child {
  text: string;
  type: string;
}

export interface Meta {
  pagination: Pagination;
}

export interface Pagination {
  page: number;
  pageSize: number;
  pageCount: number;
  total: number;
}
